
export const metadata = {
  title: "Crunchyroll",
  description: "Generated by crunchyroll",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
          {children}
      </body>
    </html>
  );
}
